### ISSUE TITLE
Streamer and meta-data improvements

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#1047]
- [x] Add stats URL (http://media.evercam.io:9991/) in admin meta-data report
- [x] Add camera name in meta-data
- [x] Sometimes streamer failed to kill stream, add a close event in the dash.
- [x] Play/drop buttons should work or remove them

**Comment by azharmalik3** [comment]
Done.
